######################################################################
# Automatically generated by qmake (3.0) Fr Dez 19 10:09:19 2014
######################################################################

TEMPLATE = app
TARGET = E8_implicit_FDM
INCLUDEPATH += .

#ToDo Qt2014
QT += widgets

# Input
HEADERS += dialog.h plotter.h
SOURCES += dialog.cpp main.cpp plotter.cpp solver.cpp
