######################################################################
# Automatically generated by qmake (2.01a) Fr 25. Jan 11:18:19 2013
######################################################################

TEMPLATE = app
#ToDo
TARGET = BHYWI-08-09-E1
DEPENDPATH += .
INCLUDEPATH += .

#ToDo Qt2014
QT += widgets

# Input
HEADERS += dialog.h plotter.h
SOURCES += dialog.cpp main.cpp plotter.cpp
