######################################################################
# Automatically generated by qmake (3.0) Fr Dez 5 16:04:27 2014
######################################################################

TEMPLATE = app
TARGET = E7_explicit_FDM
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += dialog.h plotter.h
SOURCES += dialog.cpp main.cpp plotter.cpp
