######################################################################
# Automatically generated by qmake (2.01a) Fr 25. Jan 11:18:19 2013
######################################################################
TEMPLATE = app
TARGET = BHYWI-08-01-E
DEPENDPATH += .
INCLUDEPATH += .
#ToDo Qt2014
QT += widgets
# Input
HEADERS +=
SOURCES += main.cpp
