######################################################################
# Automatically generated by qmake (2.01a) Fr 25. Jan 11:18:19 2013
######################################################################

TEMPLATE = app
#ToDo
TARGET = BHYWI-08-02-E
DEPENDPATH += .
INCLUDEPATH += .

#ToDo Qt2014
QT += widgets

# Input
HEADERS += plotter.h
SOURCES += main.cpp plotter.cpp
